### ISSUE TITLE
No references in paper?

### ISSUE THREAD

**Issue by tclune** [michaeltouati/ESVM#12]
Referencing: openjournals/joss-reviews#3618

JOSS wants:  "References: Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper citation syntax?"

**Comment by tclune** [comment]
OK - it was empty when I opened paper.md

**Comment by michaeltouati** [comment]
I think it will be better if I replace the paper.md file and the paper.bib file in the repository directly by the .pdf file generated with the JOSS tool once the paper will be published (hoping it will)
