### ISSUE TITLE
No community guidelines

### ISSUE THREAD

**Issue by tclune** [michaeltouati/ESVM#6]
The openjournals joss-reviews requires that there be a set of community guidelines.

**Comment by tclune** [comment]
Referencing: openjournals/joss-reviews#3618

**Comment by TomGoffrey** [comment]
It would be good to include in this what Fortran standard the code (should) conforms to. Note that at present, due to tab characters, the code is not strictly standards compliant.

**Comment by michaeltouati** [comment]
I have made all the modifications needed in the code to make it Fortran 90 fully compliant. For this, the intel debug compilation flag -std90 was much more helpful that the one I was using with gnu -std=f95.
