### ISSUE TITLE
Statement of need

### ISSUE THREAD

**Issue by tclune** [michaeltouati/ESVM#7]
The statement of need does not explicitly state who the target audience is?    All plasma researchers?  Students?   Researchers in a specific subdomain?

**Comment by michaeltouati** [comment]
Dear Tom,

Yes, ESVM targets the whole Plasma Physics community : researchers, teachers, students, …

**Comment by tclune** [comment]
This statement needs to be in the documentation to satisfy that requirement from JOSS.
